// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://befwwalufdtyoffztrnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZnd3YWx1ZmR0eW9mZnp0cm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTE4NTIsImV4cCI6MjA1NTQ2Nzg1Mn0.ikv9g4ERr6xkpOhDNNVYTfvhshsoshoNQYxu-gT7XJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);